"""Create vote table for votes on a pitch

Revision ID: 20945e07c9b8
Revises: e1140e5793b8
Create Date: 2017-10-31 11:08:58.295596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20945e07c9b8'
down_revision = 'e1140e5793b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('vote_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
