"""Create a one-to-many relationship between users table and lines table

Revision ID: c355194142c5
Revises: 8044ac672170
Create Date: 2017-10-30 16:28:16.698245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c355194142c5'
down_revision = '8044ac672170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lines', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_column('lines', 'user_id')
    # ### end Alembic commands ###
